<?php if (count($foxrateProductReviewList)):?>
    <h2><?php echo $this->__('Customer Reviews') ?></h2>
    <div id="userReviews">
        <div class="box-collateral box-reviews" id="customer-reviews">

            <!-- //dothis Toolbar-->
            <dl>
                <?php foreach ($foxrateProductReviewList as $review):?>
                    <div itemprop="review" itemscope itemtype="http://schema.org/Review">
                        <dt>
                            <?php echo $this->__('Review by <span itemprop="author">%s</span>', $this->htmlEscape($review['name'])) ?>
                        </dt>
                        <dd>
                            <div class="ratings-table" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                <!-- //dothis Stars-->
                                <div style="float: left">
                                    <img class="frRating-stars-small"
                                     src="<?php echo $this->getSkinUrl('images/foxrate/' . $review['stars'] . "_00.png"); ?>">
                                </div>
                                <div style="float: left; padding-left: 20px; font-size: 0.9em">
                                    <meta itemprop="worstRating" content = "1"/>
                                    <span itemprop="ratingValue"><?php echo $review['stars']; ?></span>/<span itemprop="bestRating">5</span>
                                </div>
                            </div>
                            <div style="clear: both"></div>
                            <?php if (!empty($review['comment_pros'])): ?> <p><strong><?php echo $this->__('FOXRATE_PROS'); ?></strong><br><?php echo $review['comment_pros'] ?></p><?php endif; ?>
                            <?php if (!empty($review['comment_cons'])): ?><p><strong><?php echo $this->__('FOXRATE_CONS'); ?></strong><br><?php echo $review['comment_cons'] ?></p><?php endif; ?>
                            <?php if (!empty($review['comment_conclusion'])): ?>
                                <p itemprop="name"><strong><?php echo $this->__('Conclusion'); ?></strong><br><?php echo $review['comment_conclusion']; ?></p>
                            <?php endif; ?>
                            <?php if (!empty($review['comment'])): ?><p itemprop="description"><strong><?php echo $this->__('Comment'); ?></strong><br><?php echo $review['comment']; ?></p><?php endif; ?>
                            <small class="date">
                                <meta itemprop="datePublished" content="<?php echo $this->calcReviewDate($review['date']); ?>">
                                <?php echo $this->__('(Posted on %s)', $this->calcReviewDate($review['date']), 'long') ?>
                                </meta>
                            </small>
                        </dd>
                    </div>
                <?php endforeach; ?>
            </dl>

        </div>
        <?php
        if (is_array($pages) && count($pages) > 0)
        {
            if ($pages['current']-1 > 0):    ?>
                <div class="pageNav" onclick="loadUserRevPage(<?php echo $pages['current']-1; ?> , '<?php $reviewHelper->getAjaxControllerUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');">«</div>
            <?php endif; ?>
            <?php foreach ($pages as $key => $page): ?>
            <div class="pageNav <?php if ($key == 'current') { echo 'currentPage'; } ?>"
                 onclick="loadUserRevPage(<?php echo $page; ?>, '<?php echo $reviewHelper->getAjaxControllerUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');"><?php echo $page ?></div>
        <?php endforeach; ?>
            <?php if (($pages['current'] +1 <= $foxrateProductReviews['pages_count'] ) && ($foxrateProductReviews['pages_count']  > 1)) : ?>
            <div class="pageNav" onclick="loadUserRevPage(<?php echo $pages['current'] +1 ?>, '<?php echo $reviewHelper->getAjaxControllerUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');">»</div>
        <?php endif; ?>
        <?php
        }
        ?>

    </div>
<?php endif;?>
