<?php

$processedReviews = Mage::helper('reviewcoreintegration/processreviews');
$foxrateProductReviews = $processedReviews->getRawProductReviews($this->getFoxrateProductId());
$foxrateProductReviewList = isset($foxrateProductReviews['reviews']) ? $foxrateProductReviews['reviews'] : array();

?>

<div id="foxrateProductReviews">
    <div class="prodDESC">

        <!-- tofix -->
        <input type="hidden" id="shopUrl" value="<?php echo $this->getAjaxControllerUrl(); ?>">
        <input type="hidden" id="productId" value="<?php echo $this->getFoxrateProductId(); ?>">

        <div class="frRating-top-all">
            <?php
            $foxrateReviewGeneralData = $this->getReviewTotalData($this->getFoxrateProductId());
            $pages = $processedReviews->getPageNav();

            if(empty($foxrateReviewGeneralData)): ?>
                <div class="error-msg">System error.</div>
            <?php
            endif;

            if(empty($foxrateReviewGeneralData) or isset($foxrateReviewGeneralData['error'])): ?>
                <div class="info-box"><?php echo $foxrateReviewGeneralData['error'] ?></div>
            <?php else: ?>
                <?php echo $this->getChildHtml('foxrate_summary') ?>
            <?php endif; ?>
        </div>

    </div>
</div>
<?php echo $this->getChildHtml('foxrate_review_list') ?>

<?php if (is_array($pages) && count($pages) > 0)
{
    if ($pages['current']-1 > 0):    ?>
        <div class="pageNav" onclick="loadUserRevPage(<?php echo $pages['current']-1; ?> , '<?php $this->getAjaxControllerUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');">«</div>
        <?php endif; ?>
        <?php foreach ($pages as $key => $page): ?>
        <div class="pageNav <?php if ($key == 'current') { echo 'currentPage'; } ?>"
             onclick="loadUserRevPage(<?php echo $page; ?>, '<?php echo $this->getAjaxControllerUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');"><?php echo $page ?></div>
        <?php endforeach; ?>
        <?php if (($pages['current'] +1 <= $foxrateProductReviews['pages_count'] ) && ($foxrateProductReviews['pages_count']  > 1)) : ?>
            <div class="pageNav" onclick="loadUserRevPage(<?php echo $pages['current'] +1 ?>, '<?php echo $this->getFoxrateShopUrl(); ?>', '<?php echo $this->getFoxrateProductId(); ?>');">»</div>
    <?php endif; ?>
<?php
}
?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/jquery.1.8.3.min.js')?>"></script>
<script>jQuery.noConflict();</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/foxrateProdRev.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/modalbox/js/jquery.modalbox-1.4.1.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('js/foxrate/modalbox/css/jquery.modalbox.css')?>" media="all" />
